baseurl = "https://dfontana.github.io/socialimps/"
title = "Black Mirror: Hated in the Nation"
theme = "hugo-nederburg-theme"
languageCode = "en-us"

# frontpage pagination
paginate = 5 

[params]
  # Subtitle
  slogan = "The computing implications presented."

  # Banner image
  homeimage = "img/banner.jpg"

  # Bottom footer text
  copyright = [
    "2018 Dylan Fontana, Synella Gonzales, Adam Bettigole, Ming Xu, Sam Goldman",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
  ]

  # At the end of each post is a footer, these apply:
  author = "CS3043 Team"
  authorLink = ""
  bio = [""]

  # For contact page
  email = ""

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Members"
  url = "members/"
  weight = 2

  [[menu.main]]
  name = "Credits"
  url = "credit/"
  weight = 3

  # Social media links
  [params.social]
  github = "https://github.com/dfontana/socialimps"